#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckerZ.Data.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GamesDataBase")]
	public partial class ReplayDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGameTable(GameTable instance);
    partial void UpdateGameTable(GameTable instance);
    partial void DeleteGameTable(GameTable instance);
    partial void InsertGameMoveTable(GameMoveTable instance);
    partial void UpdateGameMoveTable(GameMoveTable instance);
    partial void DeleteGameMoveTable(GameMoveTable instance);
    #endregion
		
		public ReplayDataDataContext() : 
				base(global::CheckerZ.Properties.Settings.Default.GamesDataBaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReplayDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReplayDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReplayDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReplayDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GameTable> GameTables
		{
			get
			{
				return this.GetTable<GameTable>();
			}
		}
		
		public System.Data.Linq.Table<GameMoveTable> GameMoveTables
		{
			get
			{
				return this.GetTable<GameMoveTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GameTable")]
	public partial class GameTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GameID;
		
		private int _PlayerID;
		
		private string _PlayerName;
		
		private System.DateTime _GameDate;
		
		private string _GameOutcome;
		
		private string _EndCondition;
		
		private EntitySet<GameMoveTable> _GameMoveTables;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGameIDChanging(int value);
    partial void OnGameIDChanged();
    partial void OnPlayerIDChanging(int value);
    partial void OnPlayerIDChanged();
    partial void OnPlayerNameChanging(string value);
    partial void OnPlayerNameChanged();
    partial void OnGameDateChanging(System.DateTime value);
    partial void OnGameDateChanged();
    partial void OnGameOutcomeChanging(string value);
    partial void OnGameOutcomeChanged();
    partial void OnEndConditionChanging(string value);
    partial void OnEndConditionChanged();
    #endregion
		
		public GameTable()
		{
			this._GameMoveTables = new EntitySet<GameMoveTable>(new Action<GameMoveTable>(this.attach_GameMoveTables), new Action<GameMoveTable>(this.detach_GameMoveTables));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GameID
		{
			get
			{
				return this._GameID;
			}
			set
			{
				if ((this._GameID != value))
				{
					this.OnGameIDChanging(value);
					this.SendPropertyChanging();
					this._GameID = value;
					this.SendPropertyChanged("GameID");
					this.OnGameIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayerID", DbType="Int NOT NULL")]
		public int PlayerID
		{
			get
			{
				return this._PlayerID;
			}
			set
			{
				if ((this._PlayerID != value))
				{
					this.OnPlayerIDChanging(value);
					this.SendPropertyChanging();
					this._PlayerID = value;
					this.SendPropertyChanged("PlayerID");
					this.OnPlayerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayerName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PlayerName
		{
			get
			{
				return this._PlayerName;
			}
			set
			{
				if ((this._PlayerName != value))
				{
					this.OnPlayerNameChanging(value);
					this.SendPropertyChanging();
					this._PlayerName = value;
					this.SendPropertyChanged("PlayerName");
					this.OnPlayerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameDate", DbType="DateTime NOT NULL")]
		public System.DateTime GameDate
		{
			get
			{
				return this._GameDate;
			}
			set
			{
				if ((this._GameDate != value))
				{
					this.OnGameDateChanging(value);
					this.SendPropertyChanging();
					this._GameDate = value;
					this.SendPropertyChanged("GameDate");
					this.OnGameDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameOutcome", DbType="VarChar(MAX)")]
		public string GameOutcome
		{
			get
			{
				return this._GameOutcome;
			}
			set
			{
				if ((this._GameOutcome != value))
				{
					this.OnGameOutcomeChanging(value);
					this.SendPropertyChanging();
					this._GameOutcome = value;
					this.SendPropertyChanged("GameOutcome");
					this.OnGameOutcomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndCondition", DbType="VarChar(MAX)")]
		public string EndCondition
		{
			get
			{
				return this._EndCondition;
			}
			set
			{
				if ((this._EndCondition != value))
				{
					this.OnEndConditionChanging(value);
					this.SendPropertyChanging();
					this._EndCondition = value;
					this.SendPropertyChanged("EndCondition");
					this.OnEndConditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GameTable_GameMoveTable", Storage="_GameMoveTables", ThisKey="GameID", OtherKey="GameID")]
		public EntitySet<GameMoveTable> GameMoveTables
		{
			get
			{
				return this._GameMoveTables;
			}
			set
			{
				this._GameMoveTables.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GameMoveTables(GameMoveTable entity)
		{
			this.SendPropertyChanging();
			entity.GameTable = this;
		}
		
		private void detach_GameMoveTables(GameMoveTable entity)
		{
			this.SendPropertyChanging();
			entity.GameTable = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GameMoveTable")]
	public partial class GameMoveTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MoveID;
		
		private int _MoveNumber;
		
		private int _GameID;
		
		private string _PlayerLocations;
		
		private string _ComputerLocations;
		
		private int _StartRow;
		
		private int _StartCol;
		
		private int _TargetRow;
		
		private int _TargetCol;
		
		private EntityRef<GameTable> _GameTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMoveIDChanging(int value);
    partial void OnMoveIDChanged();
    partial void OnMoveNumberChanging(int value);
    partial void OnMoveNumberChanged();
    partial void OnGameIDChanging(int value);
    partial void OnGameIDChanged();
    partial void OnPlayerLocationsChanging(string value);
    partial void OnPlayerLocationsChanged();
    partial void OnComputerLocationsChanging(string value);
    partial void OnComputerLocationsChanged();
    partial void OnStartRowChanging(int value);
    partial void OnStartRowChanged();
    partial void OnStartColChanging(int value);
    partial void OnStartColChanged();
    partial void OnTargetRowChanging(int value);
    partial void OnTargetRowChanged();
    partial void OnTargetColChanging(int value);
    partial void OnTargetColChanged();
    #endregion
		
		public GameMoveTable()
		{
			this._GameTable = default(EntityRef<GameTable>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoveID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MoveID
		{
			get
			{
				return this._MoveID;
			}
			set
			{
				if ((this._MoveID != value))
				{
					this.OnMoveIDChanging(value);
					this.SendPropertyChanging();
					this._MoveID = value;
					this.SendPropertyChanged("MoveID");
					this.OnMoveIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoveNumber", DbType="Int NOT NULL")]
		public int MoveNumber
		{
			get
			{
				return this._MoveNumber;
			}
			set
			{
				if ((this._MoveNumber != value))
				{
					this.OnMoveNumberChanging(value);
					this.SendPropertyChanging();
					this._MoveNumber = value;
					this.SendPropertyChanged("MoveNumber");
					this.OnMoveNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameID", DbType="Int NOT NULL")]
		public int GameID
		{
			get
			{
				return this._GameID;
			}
			set
			{
				if ((this._GameID != value))
				{
					if (this._GameTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGameIDChanging(value);
					this.SendPropertyChanging();
					this._GameID = value;
					this.SendPropertyChanged("GameID");
					this.OnGameIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayerLocations", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PlayerLocations
		{
			get
			{
				return this._PlayerLocations;
			}
			set
			{
				if ((this._PlayerLocations != value))
				{
					this.OnPlayerLocationsChanging(value);
					this.SendPropertyChanging();
					this._PlayerLocations = value;
					this.SendPropertyChanged("PlayerLocations");
					this.OnPlayerLocationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerLocations", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ComputerLocations
		{
			get
			{
				return this._ComputerLocations;
			}
			set
			{
				if ((this._ComputerLocations != value))
				{
					this.OnComputerLocationsChanging(value);
					this.SendPropertyChanging();
					this._ComputerLocations = value;
					this.SendPropertyChanged("ComputerLocations");
					this.OnComputerLocationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartRow", DbType="Int NOT NULL")]
		public int StartRow
		{
			get
			{
				return this._StartRow;
			}
			set
			{
				if ((this._StartRow != value))
				{
					this.OnStartRowChanging(value);
					this.SendPropertyChanging();
					this._StartRow = value;
					this.SendPropertyChanged("StartRow");
					this.OnStartRowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartCol", DbType="Int NOT NULL")]
		public int StartCol
		{
			get
			{
				return this._StartCol;
			}
			set
			{
				if ((this._StartCol != value))
				{
					this.OnStartColChanging(value);
					this.SendPropertyChanging();
					this._StartCol = value;
					this.SendPropertyChanged("StartCol");
					this.OnStartColChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetRow", DbType="Int NOT NULL")]
		public int TargetRow
		{
			get
			{
				return this._TargetRow;
			}
			set
			{
				if ((this._TargetRow != value))
				{
					this.OnTargetRowChanging(value);
					this.SendPropertyChanging();
					this._TargetRow = value;
					this.SendPropertyChanged("TargetRow");
					this.OnTargetRowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetCol", DbType="Int NOT NULL")]
		public int TargetCol
		{
			get
			{
				return this._TargetCol;
			}
			set
			{
				if ((this._TargetCol != value))
				{
					this.OnTargetColChanging(value);
					this.SendPropertyChanging();
					this._TargetCol = value;
					this.SendPropertyChanged("TargetCol");
					this.OnTargetColChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GameTable_GameMoveTable", Storage="_GameTable", ThisKey="GameID", OtherKey="GameID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public GameTable GameTable
		{
			get
			{
				return this._GameTable.Entity;
			}
			set
			{
				GameTable previousValue = this._GameTable.Entity;
				if (((previousValue != value) 
							|| (this._GameTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GameTable.Entity = null;
						previousValue.GameMoveTables.Remove(this);
					}
					this._GameTable.Entity = value;
					if ((value != null))
					{
						value.GameMoveTables.Add(this);
						this._GameID = value.GameID;
					}
					else
					{
						this._GameID = default(int);
					}
					this.SendPropertyChanged("GameTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
